name: Nikmendoza
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74539
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e5f86'
    - '#000000'
    - '#005555'
    - '#0000ff'
    - '#000080'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
