analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5328836
  brandStrength: 1
  lightness: 0.5084317
  brandColors:
    - '#FFFFFF'
    - '#1E5F85'
    - '#000000'
    - '#D9D9D9'
    - '#444444'
  rhythmicContrast: 0.5
typography_spectrum: 0.4418212
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5387858
favicon: null
name: Nikmendoza
